version: '3'
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/app/data
      - ./letsencrypt:/etc/letsencrypt
      - ./var:/app/var
    depends_on:
      - nginx-proxy-manager-db
    networks:
      - npm_network

  nginx-proxy-manager-db:
    image: 'jc21/mariadb-aria:latest'
    container_name: nginx-proxy-manager-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      TZ: Asia/Seoul
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - npm_network

  backend:
    container_name: backend
    image: popup0221/ballagain-docker-repository
    expose:
      - 8080
    ports:
      - 8080:8080

networks:
  npm_network:
    driver: bridge