version: '3'

services:
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'abc123'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'ballagain'
      MYSQL_PASSWORD: '12345'
    volumes:
      - /home/me/docker/npm/mysql:/var/lib/mysql
      
  app:
    depends_on:
      - db
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "ballagain"
      DB_MYSQL_PASSWORD: "12345"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /home/me/docker/npm/data:/data
      - /home/me/docker/npm/letsencrypt:/etc/letsencrypt