CREATE TABLE music(
    id BIGINT NOT NULL AUTO_INCREMENT,
    artist VARCHAR(50) NOT NULL,
    gender ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL,
    imageUrl VARCHAR(50),
    lylickr VARCHAR(1024) NOT NULL,
    lylicEn VARCHAR(1024) NOT NULL,
    lyricKrPro VARCHAR(1024),
    startTime VARCHAR(1024) NOT NULL,
    title VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);
