server:
  port: 9000 # 내장 톰캣 포트번호
  servlet:
    context-path: /
    session:
      cookie:
        name: ASID

spring:

  # allow method
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  # Mariadb Database 설정
  datasource:
    url: jdbc:mariadb://database-1.cf0aow4qguhl.ap-northeast-2.rds.amazonaws.com:3306/ballagain?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: 11aaAA!!
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  
  #swagger
  springdoc:
    api-docs:
      path: /docs
    swagger-ui:
      path: /swagger-ui
      display-request-duration: true
      csrf:
        enabled: true
    cache:
      disabled: true